In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import warnings as war

In [49]:
df = pd.read_csv("/Users/satwikbiswas/Documents/Python/Data/Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [50]:
df["Gender"].value_counts()
df["Gender"] = df["Gender"].replace("Fe Male","Female")

In [51]:
df["MaritalStatus"].value_counts()
df["MaritalStatus"] = df["MaritalStatus"].replace("Single","Unmarried")
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [52]:
df["Designation"].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [53]:
## finding features in side the df that have nul values
features_with_na = []
for feature in df.columns:
    if(df[feature].isnull().sum()>0):
        features_with_na.append(feature)
print(features_with_na)

['Age', 'TypeofContact', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'NumberOfChildrenVisiting', 'MonthlyIncome']

In [54]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["TypeofContact"] = df["TypeofContact"].fillna(df["TypeofContact"].mode()[0])
df["DurationOfPitch"] = df["DurationOfPitch"].fillna(df["DurationOfPitch"].median())
df["NumberOfFollowups"] = df["NumberOfFollowups"].fillna(df["NumberOfFollowups"].mode()[0])
df["PreferredPropertyStar"] = df["PreferredPropertyStar"].fillna(df["PreferredPropertyStar"].mode()[0])
df["NumberOfTrips"] = df["NumberOfTrips"].fillna(df["NumberOfTrips"].median())
df["NumberOfChildrenVisiting"] = df["NumberOfChildrenVisiting"].fillna(df["NumberOfChildrenVisiting"].mode()[0])
df["MonthlyIncome"] = df["MonthlyIncome"].fillna(df["MonthlyIncome"].median())

In [55]:
df["NumberOfTotalVisiting"] = df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]
df.drop(["NumberOfChildrenVisiting","NumberOfPersonVisiting"],inplace=True,axis=1)

In [56]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,NumberOfTotalVisiting
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [57]:
from sklearn.model_selection import train_test_split

X = df.drop(["ProdTaken"],axis=1)
y = df["ProdTaken"]

In [58]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=14,shuffle=True)

print(X_train.shape)
print(X_test.shape)

(3910, 18)
(978, 18)

In [59]:
## seperating the numerical and catagorical data

numerical_features = [feature for feature in df.columns if df[feature].dtype != "object"]
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'object']
print(numerical_features)
print(categorical_features)

numerical_features.remove("ProdTaken")

['CustomerID', 'ProdTaken', 'Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'NumberOfTotalVisiting']
['TypeofContact', 'Occupation', 'Gender', 'ProductPitched', 'MaritalStatus', 'Designation']

In [60]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

colTrans =  ColumnTransformer([
    ("cat",OneHotEncoder(handle_unknown="ignore",drop="first"),categorical_features),
    ("num",StandardScaler(),numerical_features)
])

X_train = colTrans.fit_transform(X_train)
X_test =  colTrans.transform(X_test)

In [61]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,-0.721469,-0.163783,1.300711,-0.733058,-0.120509,1.553978,0.669374,0.785093,2.617447,0.647357
1,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,-0.721469,-0.997005,0.294423,-0.733058,-0.671610,-0.643510,1.401677,0.785093,2.784961,0.647357
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,-0.721469,-0.997005,0.294423,-0.733058,1.532793,1.553978,-0.795233,-1.273735,0.562908,0.647357
3,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,-0.721469,1.026534,-0.711865,-0.733058,-0.120509,-0.643510,-0.062929,0.785093,-0.147181,-0.769870
4,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721469,-0.758941,0.294423,0.520224,-0.120509,-0.643510,-0.062929,0.785093,-0.658597,1.355971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.452668,-0.877973,0.294423,-0.733058,0.981692,-0.643510,-0.062929,0.785093,0.585004,1.355971
3906,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.721469,-0.997005,2.307000,1.773507,-0.120509,-0.643510,-1.527536,0.785093,0.023165,0.647357
3907,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721469,0.907503,-0.711865,0.520224,-0.671610,-0.643510,-0.062929,0.785093,-0.463511,0.647357
3908,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.452668,1.264598,-0.711865,-0.733058,-0.120509,-0.643510,-0.062929,0.785093,-0.228766,-1.478483
3909,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.452668,-0.639910,0.294423,-0.733058,-0.671610,-0.643510,-0.795233,0.785093,1.081878,1.355971

In [62]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

In [63]:
models = {
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Logistic Regression": LogisticRegression(),
    "Adaboost": AdaBoostClassifier()
}

for name, model in models.items():
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Corrected print statements
    print(f"Accuracy for {name} on train data: {accuracy_score(y_train, y_train_pred)*100}")
    print(f"Accuracy for {name} on test data: {accuracy_score(y_test, y_test_pred)*100}\n")
    print(classification_report(y_true=y_test,y_pred=y_test_pred))
    print("#"*100)

Accuracy for Random Forest on train data: 100.0
Accuracy for Random Forest on test data: 90.69529652351737

              precision    recall  f1-score   support

           0       0.90      0.99      0.94       762
           1       0.96      0.60      0.74       216

    accuracy                           0.91       978
   macro avg       0.93      0.80      0.84       978
weighted avg       0.91      0.91      0.90       978

####################################################################################################
Accuracy for Decision Tree on train data: 100.0
Accuracy for Decision Tree on test data: 87.8323108384458

              precision    recall  f1-score   support

           0       0.92      0.93      0.92       762
           1       0.74      0.70      0.72       216

    accuracy                           0.88       978
   macro avg       0.83      0.81      0.82       978
weighted avg       0.88      0.88      0.88       978

####################################################################################################
Accuracy for Logistic Regression on train data: 84.83375959079284
Accuracy for Logistic Regression on test data: 81.90184049079755

              precision    recall  f1-score   support

           0       0.83      0.97      0.89       762
           1       0.72      0.29      0.42       216

    accuracy                           0.82       978
   macro avg       0.78      0.63      0.65       978
weighted avg       0.81      0.82      0.79       978

####################################################################################################
Accuracy for Adaboost on train data: 85.9079283887468
Accuracy for Adaboost on test data: 83.12883435582822

              precision    recall  f1-score   support

           0       0.83      0.99      0.90       762
           1       0.87      0.28      0.42       216

    accuracy                           0.83       978
   macro avg       0.85      0.63      0.66       978
weighted avg       0.84      0.83      0.80       978

####################################################################################################

In [64]:
rf_params = {
    "n_estimators": [50, 100, 200, 300, 400, 500],   # More options for tree count
    "max_depth": [10, 20, 30, 40, 50, None],        # Deeper trees for complex patterns
    "max_features": ["sqrt", "log2", None],         # Feature selection per split
    "bootstrap": [True, False],                     # Whether to use bootstrap sampling
    "min_samples_split": [2, 5, 10],                # Controls when to split a node
    "min_samples_leaf": [1, 2, 4]                   # Minimum samples in a leaf
}
ada_params = {
    "n_estimators": [50, 100, 200, 300],
    "learning_rate": [0.01, 0.1, 0.5, 1.0],
    "estimator": [DecisionTreeClassifier(max_depth=1), DecisionTreeClassifier(max_depth=3)]
}

In [65]:
from sklearn.model_selection import RandomizedSearchCV

In [66]:
random_cv = [
    ["rf",RandomForestClassifier(n_jobs=-1),rf_params],
    ["ada",AdaBoostClassifier(),ada_params]
]

for name,model,param_grid in random_cv:

    random = RandomizedSearchCV(estimator=model,cv=5,random_state=12,n_jobs=-1,param_distributions=param_grid,scoring="accuracy")
    random.fit(X_train,y_train)
    print(f"{name}:")
    print(random.best_params_)
    print(random.best_score_)
    print(random.best_estimator_)
    y_pred = random.predict(X_test)
    print(classification_report(y_true=y_test,y_pred=y_pred))
    print("#"*100)

rf:
{'n_estimators': 50, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'max_depth': 30, 'bootstrap': True}
0.916624040920716
RandomForestClassifier(max_depth=30, max_features=None, n_estimators=50,
                       n_jobs=-1)
              precision    recall  f1-score   support

           0       0.92      0.99      0.95       762
           1       0.94      0.70      0.81       216

    accuracy                           0.93       978
   macro avg       0.93      0.85      0.88       978
weighted avg       0.93      0.93      0.92       978

####################################################################################################
ada:
{'n_estimators': 100, 'learning_rate': 0.5, 'estimator': DecisionTreeClassifier(max_depth=3)}
0.8659846547314578
AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=3),
                   learning_rate=0.5, n_estimators=100)
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       762
           1       0.82      0.39      0.53       216

    accuracy                           0.85       978
   macro avg       0.83      0.68      0.72       978
weighted avg       0.84      0.85      0.83       978

####################################################################################################

### Adaboost Regressor

In [8]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [9]:
diabetes = load_diabetes()
X = pd.DataFrame(diabetes["data"])
y = diabetes["target"]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=10,shuffle=True,test_size=0.20)
print(X_train.shape,X_test.shape)

(353, 10) (89, 10)

In [86]:
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.metrics import r2_score

models = {
    "Random Forest":RandomForestRegressor(n_jobs=-1,random_state=42, verbose=1),
    "Adaboost":AdaBoostRegressor(random_state=12)
}

for name,model in models.items():
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Corrected print statements
    print(f"Accuracy for {name} on train data: {r2_score(y_train, y_train_pred)*100}")
    print(f"Accuracy for {name} on test data: {r2_score(y_test, y_test_pred)*100}\n")
    print("#"*100)

Accuracy for Random Forest on train data: 91.82354686068005
Accuracy for Random Forest on test data: 47.56798852444316

####################################################################################################
Accuracy for Adaboost on train data: 62.614523999462676
Accuracy for Adaboost on test data: 44.60063513953638

####################################################################################################

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished

In [87]:
from sklearn.model_selection import GridSearchCV


rf_params = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

rf_grid = GridSearchCV(RandomForestRegressor(n_jobs=-1, random_state=42), rf_params, cv=5,scoring="r2")
rf_grid.fit(X_train, y_train)

print("Best parameters for Random Forest:", rf_grid.best_params_)
print("BEst accuracy:",rf_grid.best_score_)

Best parameters for Random Forest: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 200}
BEst accuracy: 0.43994308667721516

### Applying polynomial regression to check which is better for classification

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV


poly = PolynomialFeatures(include_bias=True,degree=2)
regression = LinearRegression(n_jobs=-1)


pipeline = Pipeline([
    ('poly-features', poly),
    ('line-reg', regression)
])


param_grid = {
    "poly-features__degree": list(range(1, 7))  # Degrees from 1 to 12
}


model = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=5, n_jobs=-1, scoring="r2")
model.fit(X_train, y_train)


print("Best Polynomial Degree:", model.best_params_["poly-features__degree"])
print("Best R² Score:", model.best_score_)

Best Polynomial Degree: 1
Best R² Score: 0.47107405063441526

In [15]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score

# Create a pipeline: Scaling + SVR
pipeline = Pipeline([
    ("scaler", StandardScaler()),  # Scaling is required for SVR
    ("svr", SVR())
])

# Define hyperparameter grid
param_grid = {
    "svr__C": [0.1, 1, 10, 100],  # Regularization parameter
    "svr__epsilon": [0.01, 0.1, 0.5, 1],  # Margin of error
    "svr__gamma": ["scale", "auto", 0.01, 0.1, 1]  # Kernel coefficient
}

# Perform Grid Search
model = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=5, n_jobs=-1, scoring="r2")
model.fit(X_train, y_train)

# Get best parameters and score
print("Best Parameters for SVR:", model.best_params_)
print("Best R² Score:", model.best_score_)

# Evaluate on test set
y_test_pred = model.best_estimator_.predict(X_test)
print("Test R² Score:", r2_score(y_test, y_test_pred))

Best Parameters for SVR: {'svr__C': 100, 'svr__epsilon': 0.5, 'svr__gamma': 0.01}
Best R² Score: 0.48523087785564983
Test R² Score: 0.5374962257628191